name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  check:
    name: "Run :check"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo."
        uses: actions/checkout@v4
      - name: "Set up Java."
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: "Setup Gradle."
        uses: gradle/gradle-build-action@v2
      - name: "Run build with Gradle Wrapper."
        shell: bash
        env:
          FLIGHTAWARE_TOKEN: ${{ secrets.FLIGHTAWARE_TOKEN }}
        run: ./gradlew check

      - name: "Upload Lint results."
        uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: "Lint"
          if-no-files-found: error
          path: |
            app/build/reports/lint-*

      - name: "Upload test results."
        uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: "Unit Tests"
          if-no-files-found: error
          path: |
            **/build/reports/tests/

  assemble:
    name: "Assemble :check"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo."
        uses: actions/checkout@v4
      - name: "Set up Java."
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: "Setup Gradle."
        uses: gradle/gradle-build-action@v2
      - name: "Run build with Gradle Wrapper."
        shell: bash
        env:
          FLIGHTAWARE_TOKEN: ${{ secrets.FLIGHTAWARE_TOKEN }}
        run: ./gradlew assemble
      - name: "Upload APKs."
        uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: "APKs"
          if-no-files-found: error
          path: |
            app/build/outputs/apk/*/*.apk
